export const FETCH_ALL_NOTIFICATIONS = 'FETCH_ALL_ NOTIFICATIONS';
export const START_FETCH_ALL_NOTIFICATIONS = 'START_FETCH_ALL_NOTIFICATIONS';
export const FETCH_ONE_NOTIFICATION = 'FETCH_ONE-NOTIFICATION';
export const START_FETCH_ONE_NOTIFICATION = 'START_FETCH_ONE_NOTIFICATION';
